### ISSUE TITLE
Can you share the UNDD dataset?

### ISSUE THREAD

**Issue by leftthomas** [sauradip/night_image_semantic_segmentation#2]

**Comment by sauradip** [comment]
hi , 

You can find one of our testing Split here [https://drive.google.com/drive/folders/1KBn3LIoD5rvNFDe2aZCH-4mNo6iXSuGX?usp=sharing](Link). I will upload the training split after April 2021. You can use this test split for fine-tuning Cityscapes/KITTI , it contains images from real world driving dataset.

**Comment by leftthomas** [comment]
@sauradip I have notice the test split, but I want to use the training split, anyway, thanks
